### ISSUE TITLE
Merging approaches

### ISSUE THREAD

**Issue by StrangeTcy** [epfml/dynamic-sparse-flash-attention#1]
I'm currently working on integrating landmark attention and original flash attention into Llama. So, I was wondering whether your approach and landmark attention are mergeable as well (the landmark attention paper hints it should be, I think), and whether you plan to release an official implementation

**Comment by martinjaggi** [comment]
as landmark attention is now compatible with flash attention through the [triton implementation provided](https://github.com/epfml/landmark-attention/commit/098c60a641ed54b52edb01267d4ca3d899c2ae3b), can we close this?
