### ISSUE TITLE
FlashAttention 1 or FlashAttention 2?

### ISSUE THREAD

**Issue by DefTruth** [epfml/dynamic-sparse-flash-attention#3]
May I ask, are you comparing FA1 or FA2? FA2 is 2x times faster than FA1 according to [flashattn2.pdf](https://arxiv.org/pdf/2307.08691.pdf)

**Comment by jkobject** [comment]
from reading the code it seems like only a tiny subset of flashattention,lots of bells and whistles are not there. 

Also let me know what you think but It feels like it might even be easier to do a pull request, adding it to the flash attention repo.

**Comment by mpagli** [comment]
Sorry for the slow answer, we did this work before FA2 was published. In the paper, we compare to FA1. We assume that the speedups would transfer to FA2. 

We'd love to push our suggested changes to the flash attention repo. We'll try to allocate some time for that in the next month.

**Comment by jkobject** [comment]
Hi Mateo, Thanks for getting back to us!

I tried to reach out on LinkedIn. Let me know if you would have some time to chat quickly. I have a project idea in mind regarding applying this to genomics and applying your work to another model. :) 

Best,
